homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.gibranharahap, name='gibranharahap'),
    path('about/', views.about, name='about'),
	path('reminder/', views.reminder, name='reminder'),
	path('schedule/', views.schedule, name='schedule'),
	path('addschedule/', views.addschedule, name ='addschedule'),
    path('resetAll/', views.resetAll, name ='resetAll'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', include('homepage.urls')),
]

homepage/models.py
from django.db import models
from datetime import datetime

# Create your models here.

class Schedule(models.Model):

    activity = models.CharField(max_length=15)
    description = models.CharField(max_length=40)
    date = models.DateTimeField(default=datetime.now)
    time = models.TimeField()
    place = models.CharField(max_length=15)
    category = models.CharField(max_length=20)

homepage/forms.py
from django import forms
from .models import Schedule

class scheduleForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['activity','description', 'date', 'time', 'place', 'category']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'time': forms.TimeInput(attrs={'type': 'time'})}

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.Meta.fields:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

homepage/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse

from .models import Schedule
from . import forms

# Create your views here.

def gibranharahap(request):
    return render(request, 'gibranharahap.html')

def about(request):
    return render(request, 'about.html')

def reminder(request):
    return render(request, 'reminder.html')
	
def schedule(request):
    schedules = Schedule.objects.all().order_by('date')
    return render(request, 'schedule.html', {'schedules': schedules})

def addschedule(request):
    if request.method == 'POST': 
        form = forms.scheduleForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/schedule')

    else:
        form = forms.scheduleForm()
    return render(request, 'addschedule.html', {'form': form})

def resetAll(request):
    Schedule.objects.all().delete()
    schedules =[]
    return render(request, 'schedule.html', {'schedules': schedules})

homepage/templates/about.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type=text/css href="{% static 'css/websites.css' %}"/>
    <title>about</title>
  </head>
  <body class="body">
	<div class="container-fluid">
		<div class="row">
			<div class="col">
				<nav class="navbar navbar-expand-lg navbar-dark">
					<a class="navbar-brand" id="gibranharahap" href="{% url 'homepage:gibranharahap' %}">gibranharahap</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
						<div class="navbar-nav">
							<a class="nav-item nav-link" id="about" href="{% url 'homepage:about' %}">about</a>
							<a class="nav-item nav-link" id="rem" href="{% url 'homepage:reminder' %}">????</a>
							<a class="nav-item nav-link" id="schedule" href="{% url 'homepage:schedule' %}">schedule</a>
						</div>
					</div>
				</nav>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<img id="foto" src="{% static 'images/foto.JPG' %}" class="img-fluid" alt="foto">
			</div>
		</div>
		<div class="row">
			<div class="col">
				<p id="hello">hello!</p>
				<p id="desc">
				my name is Gibran Ridha Parlindungan Harahap<br><br>
				education:<br>
				- university of indonesia, information systems (2018 - present)<br>
				- sman 1 tangerang (2015 - 2018)<br><br>
				experience:<br>
				- compfest, staff of playground (2019 - present)<br><br>
				skill:<br>
				- programming (python, java)<br>
				- microsoft office<br>
				- teamworking<br>
				- hard-worker and totality<br>
				</p>
			</div>
		</div>
		<div class="row blue">
			<div class="col col-sm"></div>
			<div class="col col-sm-1">
				<a href="mailto:gibranharahap@gmail.com">
					<img id="email" src="{% static 'images/email.png' %}" class="img-fluid" alt="email"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://twitter.com/gibranharahap">
					<img id="twitter" src="{% static 'images/twitter.png' %}" class="img-fluid" alt="twitter"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://www.linkedin.com/in/gibranharahap" >
					<img id="linkedin" src="{% static 'images/linkedin.png' %}" class="img-fluid" alt="linkedin"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://open.spotify.com/user/gibranharahap8?si=WqA3pPyQRgqX1yCX1G7e7A">
					<img id="spotify" src="{% static 'images/spotify.png' %}" class="img-fluid" alt="spotify"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://www.instagram.com/gibranharahap">
					<img id="instagram" src="{% static 'images/instagram.png' %}" class="img-fluid" alt="instagram"></a>
			</div>
			<div class="col col-sm"></div>
		</div>
	</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/addschedule.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type=text/css href="{% static 'css/websites.css' %}"/>
    <title>addschedule</title>
  </head>
  <body class="body">
	<div class="container-fluid">
		<div class="row">
			<div class="col">
				<nav class="navbar navbar-expand-lg navbar-dark">
					<a class="navbar-brand" id="gibranharahap" href="{% url 'homepage:gibranharahap' %}">gibranharahap</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
						<div class="navbar-nav">
							<a class="nav-item nav-link" id="about" href="{% url 'homepage:about' %}">about</a>
							<a class="nav-item nav-link" id="rem" href="{% url 'homepage:reminder' %}">????</a>
							<a class="nav-item nav-link" id="schedule" href="{% url 'homepage:schedule' %}">schedule</a>
						</div>
					</div>
				</nav>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<p id="add">add schedule</p>
					{% block content %}
						<form method="POST" class="post-form">
							{% csrf_token %}
							{{ form.as_p }}
							<div style="text-align:center"><button type="submit" id="button" class="save btn btn-default">submit</button></div>
						</form>
					{% endblock %}
			</div>
		</div>
	
		<div class="row blue">
			<div class="col col-sm"></div>
			<div class="col col-sm-1">
				<a href="mailto:gibranharahap@gmail.com">
					<img id="email" src="{% static 'images/email.png' %}" class="img-fluid" alt="email"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://twitter.com/gibranharahap">
					<img id="twitter" src="{% static 'images/twitter.png' %}" class="img-fluid" alt="twitter"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://www.linkedin.com/in/gibranharahap" >
					<img id="linkedin" src="{% static 'images/linkedin.png' %}" class="img-fluid" alt="linkedin"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://open.spotify.com/user/gibranharahap8?si=WqA3pPyQRgqX1yCX1G7e7A">
					<img id="spotify" src="{% static 'images/spotify.png' %}" class="img-fluid" alt="spotify"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://www.instagram.com/gibranharahap">
					<img id="instagram" src="{% static 'images/instagram.png' %}" class="img-fluid" alt="instagram"></a>
			</div>
			<div class="col col-sm"></div>
		</div>
	</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/gibranharahap.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type=text/css href="{% static 'css/websites.css' %}"/>
    <title>gibranharahap</title>
  </head>
  <body class="body">
	<div class="container-fluid">
		<div class="row">
			<div class="col">
				<nav class="navbar navbar-expand-lg navbar-dark">
					<a class="navbar-brand" id="gibranharahap" href="{% url 'homepage:gibranharahap' %}">gibranharahap</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
						<div class="navbar-nav">
							<a class="nav-item nav-link" id="about" href="{% url 'homepage:about' %}">about</a>
							<a class="nav-item nav-link" id="rem" href="{% url 'homepage:reminder' %}">????</a>
							<a class="nav-item nav-link" id="schedule" href="{% url 'homepage:schedule' %}">schedule</a>
						</div>
					</div>
				</nav>
				<img id="gif" src="{% static 'images/gif.gif' %}" class="img-fluid" alt="cool gif">
			</div>
		</div>
		<div class="row">
			<div class="col">
				<p id="quotes">
				sungguh<br>
				ku belum tahu apa yang mendorong ku di belakang sana<br>
				sungguh<br>
				ku belum tahu apa yang sedang terjadi disini<br>
				sungguh<br> 
				ku belum tahu apa yang terhampar di depan sana<br>
				<br>
				sungguh<br>
				ku kan bersungguh-sungguh<br>
				</p>
			</div>
		</div>
		<div class="row blue">
			<div class="col col-sm"></div>
			<div class="col col-sm-1">
				<a href="mailto:gibranharahap@gmail.com">
					<img id="email" src="{% static 'images/email.png' %}" class="img-fluid" alt="email"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://twitter.com/gibranharahap">
					<img id="twitter" src="{% static 'images/twitter.png' %}" class="img-fluid" alt="twitter"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://www.linkedin.com/in/gibranharahap" >
					<img id="linkedin" src="{% static 'images/linkedin.png' %}" class="img-fluid" alt="linkedin"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://open.spotify.com/user/gibranharahap8?si=WqA3pPyQRgqX1yCX1G7e7A">
					<img id="spotify" src="{% static 'images/spotify.png' %}" class="img-fluid" alt="spotify"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://www.instagram.com/gibranharahap">
					<img id="instagram" src="{% static 'images/instagram.png' %}" class="img-fluid" alt="instagram"></a>
			</div>
			<div class="col col-sm"></div>
		</div>
	</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/reminder.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type=text/css href="{% static 'css/websites.css' %}"/>
    <title>????</title>
  </head>
  <body class="body">
	<div class="container-fluid">
		<div class="row">
			<div class="col">
				<nav class="navbar navbar-expand-lg navbar-dark">
					<a class="navbar-brand" id="gibranharahap" href="{% url 'homepage:gibranharahap' %}">gibranharahap</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
						<div class="navbar-nav">
							<a class="nav-item nav-link" id="about" href="{% url 'homepage:about' %}">about</a>
							<a class="nav-item nav-link" id="rem" href="{% url 'homepage:reminder' %}">????</a>
							<a class="nav-item nav-link" id="schedule" href="{% url 'homepage:schedule' %}">schedule</a>
						</div>
					</div>
				</nav>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<img id="reminder" src="{% static 'images/reminder.jpg' %}" class="img-fluid" alt="reminder">
			</div>
		</div>
		<div class="row">
			<div class="col">
				<p id="reminds">there's no point in buying concrete shoes, i'll refuse</p>
			</div>
		</div>
		<div class="row blue">
			<div class="col col-sm"></div>
			<div class="col col-sm-1">
				<a href="mailto:gibranharahap@gmail.com">
					<img id="email" src="{% static 'images/email.png' %}" class="img-fluid" alt="email"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://twitter.com/gibranharahap">
					<img id="twitter" src="{% static 'images/twitter.png' %}" class="img-fluid" alt="twitter"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://www.linkedin.com/in/gibranharahap" >
					<img id="linkedin" src="{% static 'images/linkedin.png' %}" class="img-fluid" alt="linkedin"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://open.spotify.com/user/gibranharahap8?si=WqA3pPyQRgqX1yCX1G7e7A">
					<img id="spotify" src="{% static 'images/spotify.png' %}" class="img-fluid" alt="spotify"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://www.instagram.com/gibranharahap">
					<img id="instagram" src="{% static 'images/instagram.png' %}" class="img-fluid" alt="instagram"></a>
			</div>
			<div class="col col-sm"></div>
		</div>
	</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

homepage/templates/schedule.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" type=text/css href="{% static 'css/websites.css' %}"/>
    <title>schedule</title>
  </head>
  <body class="body">
	<div class="container-fluid">
		<div class="row">
			<div class="col">
				<nav class="navbar navbar-expand-lg navbar-dark">
					<a class="navbar-brand" id="gibranharahap" href="{% url 'homepage:gibranharahap' %}">gibranharahap</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
						<div class="navbar-nav">
							<a class="nav-item nav-link" id="about" href="{% url 'homepage:about' %}">about</a>
							<a class="nav-item nav-link" id="rem" href="{% url 'homepage:reminder' %}">????</a>
							<a class="nav-item nav-link" id="schedule" href="{% url 'homepage:schedule' %}">schedule</a>
						</div>
					</div>
				</nav>
			</div>
		</div>
		<div class="row">
			<div class="col">
				<p id="my">my schedules</p>
			</div>
		</div>
		<div class="row">
			<div style="text-align:center" class="col">
				<a id="sched" href="{% url 'homepage:addschedule' %}">add schedule</a>
				<a id="sched" href="{% url 'homepage:resetAll' %}">reset</a>
			</div>
		</div>
		<div class="row">
			{% for schedule in schedules %}
				<div style="text-align:center" class="col">
					<p id="sched">{{ schedule.activity }}<br>
					   {{ schedule.description }}<br>
                       {{ schedule.date.date }}<br>
                       {{ schedule.time }}<br>
                       {{ schedule.place }}<br>
                       {{ schedule.category }}</p>
				</div>
			{% endfor %}
		</div>
		<div class="row blue">
			<div class="col col-sm"></div>
			<div class="col col-sm-1">
				<a href="mailto:gibranharahap@gmail.com">
					<img id="email" src="{% static 'images/email.png' %}" class="img-fluid" alt="email"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://twitter.com/gibranharahap">
					<img id="twitter" src="{% static 'images/twitter.png' %}" class="img-fluid" alt="twitter"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://www.linkedin.com/in/gibranharahap" >
					<img id="linkedin" src="{% static 'images/linkedin.png' %}" class="img-fluid" alt="linkedin"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://open.spotify.com/user/gibranharahap8?si=WqA3pPyQRgqX1yCX1G7e7A">
					<img id="spotify" src="{% static 'images/spotify.png' %}" class="img-fluid" alt="spotify"></a>
			</div>
			<div class="col col-sm-1">
				<a href="https://www.instagram.com/gibranharahap">
					<img id="instagram" src="{% static 'images/instagram.png' %}" class="img-fluid" alt="instagram"></a>
			</div>
			<div class="col col-sm"></div>
		</div>
	</div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>